# Change these first
owner: dgamboaestrada # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
sites:
  - name: danielgamboa.mx
    url: https://danielgamboa.mx
  - name: ItronicsStore
    url: $ITRONICS_STORE_URL
    headers:
      - "CF-Access-Client-Id: $CF_ACESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACESS_CLIENT_SECRET"
  - name: ItronicsWorkshop
    url: $ITRONICS_WORKSHOP_URL
    headers:
      - "CF-Access-Client-Id: $CF_ACESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACESS_CLIENT_SECRET"
  - name: Homer
    url: https://homer.gamboa.xyz
    headers:
      - "CF-Access-Client-Id: $CF_ACESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACESS_CLIENT_SECRET"
  - name: Nextcloud
    url: https://nextcloud.gamboa.xyz
    headers:
      - "CF-Access-Client-Id: $CF_ACESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACESS_CLIENT_SECRET"
  - name: Pi-hole
    url: https://pihole.gamboa.xyz
    headers:
      - "CF-Access-Client-Id: $CF_ACESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACESS_CLIENT_SECRET"
  - name: ProxyManager
    url: https://proxy.gamboa.xyz
    headers:
      - "CF-Access-Client-Id: $CF_ACESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACESS_CLIENT_SECRET"
  - name: Protainer
    url: https://portainer.gamboa.xyz
    headers:
      - "CF-Access-Client-Id: $CF_ACESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACESS_CLIENT_SECRET"
  - name: Jellyfin
    url: https://jellyfin.gamboa.xyz
    headers:
      - "CF-Access-Client-Id: $CF_ACESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACESS_CLIENT_SECRET"
  - name: RuTorrent
    url: https://rutorrent.gamboa.xyz
    headers:
      - "CF-Access-Client-Id: $CF_ACESS_CLIENT_ID"
      - "CF-Access-Client-Secret: $CF_ACESS_CLIENT_SECRET"
assignees: # Users to assign downtime issues (optional)
  - dgamboaestrada
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gamboa.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
